"""
tests/suite/README.md

ACIS-X Performance & Evidence Suite
=====================================

PURPOSE
-------
These tests provide REPORT-GRADE, CITEABLE evidence of ACIS-X's performance,
intelligence superiority, and system integrity.

They answer:
  • How fast is a single invoice through the pipeline?  (stage-by-stage waterfall)
  • Is ACIS-X meaningfully better than a naive rule-based baseline?  (F1, Spearman ρ)
  • Does multi-signal fusion outperform any single signal alone?
  • Does external enrichment add information, or is it noise?
  • What is the P95 processing latency under mocked conditions?
  • How quickly does the system self-heal (MTTR)?

HONESTY POLICY
--------------
• ACIS-X agents are exercised through their actual public API — no mocks that
  guarantee a win.
• Ground truth is generated by a deterministic function that neither system
  is optimised against.
• No thresholds are tuned post-hoc. If the implementation regresses, tests fail.

STRUCTURE
---------
suite/
  conftest.py                    Shared fixtures (RecordingKafka, event builders)
  test_unit_core.py              Monotonicity proofs, decision thresholds, TTL correctness
  test_lifecycle_trace.py        Invoice/payment end-to-end timing (waterfall + chart)
  test_intelligence_comparison.py  ACIS-X vs baselines (F1, Spearman ρ, ablation)
  test_performance.py            P95 latency, MTTR, duplicate prevention at scale
  test_integration_contracts.py  Agent payload contracts, correlation ID propagation

RUNNING
-------
All suite tests:
    pytest tests/suite/ -v --tb=short

By category (markers):
    pytest tests/suite/ -m unit          # monotonicity, decision thresholds, TTL
    pytest tests/suite/ -m lifecycle     # timing waterfall
    pytest tests/suite/ -m intelligence  # ACIS-X vs baselines
    pytest tests/suite/ -m performance   # P95, MTTR, dedup
    pytest tests/suite/ -m integration   # payload contracts

With log output (shows latency tables):
    pytest tests/suite/ -v -s --log-cli-level=INFO

Output charts (require matplotlib):
    tests/outputs/lifecycle_stage_waterfall.png  (generated by test_lifecycle_trace)

COVERAGE MAPPING FROM regular_tests/
--------------------------------------
The following regular_tests/ files have suite equivalents.  The regular_tests
version is the quick smoke test; the suite version provides statistical rigor.

regular_tests/ file                    suite/ equivalent
─────────────────────────────────────  ────────────────────────────────────────
test_overpayment_clamping              test_unit_core (TestDBAgentContracts)
test_exactly_once_processing           test_unit_core (TestDBAgentContracts)
test_risk_score_monotonicity           test_unit_core (TestRiskScoreMonotonicity)
test_enrichment_ablation               test_intelligence_comparison (ablation)
test_integration_pipeline              test_integration_contracts (persistence)

DELETED FILES (superseded)
---------------------------
test_pipeline_latency.py     → replaced by suite/test_performance.py (same methodology,
                               cleaner, with statistics and structured assertions)
test_mttr_under_fault_injection.py → replaced by suite/test_performance.py::TestSelfHealingMTTR
"""
